SELECT ?lEndTime ?lDescription
WHERE
{
  ?nAction
    uco-action:actionReferences [
      a uco-action:ActionReferences ;
      uco-action:endTime ?lEndTime ;
    ] ;
    uco-core:description ?lDescription ;
    .

  { ?nAction a uco-action:Action . }
  UNION
  { ?nAction a uco-investigation:InvestigativeAction . }
}
ORDER BY ?lEndTime
