SELECT ?lEndTime ?lDescription
WHERE
{
  ?nAction
    a uco-investigation:InvestigativeAction ;
    uco-action:actionReferences [
      a uco-action:ActionReferences ;
      uco-action:endTime ?lEndTime ;
    ] ;
    uco-core:description ?lDescription ;
    .

}
ORDER BY ?lEndTime
