SELECT DISTINCT ?nLocation ?lRoomId ?lDescription
WHERE
{
  ?nAction
    a case-investigation:InvestigativeAction ;
    uco-core:hasFacet [
      a uco-action:ActionReferencesFacet ;
      uco-action:location ?nLocation ;
    ] ;
    .

  ?nLocation
    a uco-location:Location ;
    uco-core:description ?lDescription ;
    uco-core:hasFacet [
      a uco-location:SimpleAddressFacet ;
      drafting:roomId ?lRoomId ;
    ]
    .

}
ORDER BY ?nLocation
