SELECT ?lStartTime ?lEndTime ?lDescription
WHERE
{
  ?nAction
    a case-investigation:InvestigativeAction ;
    uco-core:facets ?nActionReferences ;
    uco-core:description ?lDescription ;
    .

  ?nActionReferences
    a uco-action:ActionReferences ;
    uco-action:endTime ?lEndTime ;
    .

  OPTIONAL
  {
    ?nActionReferences
      uco-action:startTime ?lStartTime ;
      .
  }
}
ORDER BY ?lEndTime
