PREFIX case-investigation: <https://ontology.caseontology.org/case/investigation/>
PREFIX uco-action: <https://ontology.unifiedcyberontology.org/uco/action/>
PREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/>

SELECT ?lStartTime ?lEndTime ?lDescription
WHERE
{
  ?nAction
    a case-investigation:InvestigativeAction ;
    uco-core:description ?lDescription ;
    uco-action:endTime ?lEndTime ;
    .

  OPTIONAL
  {
    ?nAction
      uco-action:startTime ?lStartTime ;
      .
  }
}
ORDER BY ?lEndTime
